# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('ip', models.IntegerField()),
            ],
        ),
    ]
