# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dbinfo',
            name='hostname',
        ),
    ]
