# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_remove_dbinfo_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.IntegerField(default=0),
        ),
    ]
