# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20160428_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbinfo',
            name='db_type',
            field=models.CharField(max_length=100),
        ),
    ]
